### ISSUE TITLE
File naming question / Feature request

### ISSUE THREAD

**Issue by pcause** [jamesgreenblue/obsidian-quicknote#2]
It isn't clear but I assume for the file one can give a complete path.  For example I have my daily notes in this folder:

Notes/me/Inbox/DailyNotes

and use this for the new note naming

YYYY/MM-MMMM/YYYY-MM-DD

so that a new daily note gets created in : Notes/me/Inbox/DailyNotes/YYYY/MM-MMMM/YYYY-MM-DD

for today that would be : : Notes/me/Inbox/DailyNotes/2023/08-August/2023-08-26

Can I enter Notes/me/Inbox/DailyNotes/YYYY/MM-MMMM/YYYY-MM-DD in settings as location of a note to add?

**Comment by jamesgreenblue** [comment]
Hi @pcause,

For simplicity this plug-in follows the `Default location for new notes` Obsidian setting.

That said, it is technically possible to provide a sub path using square brackets – try entering `Notes[/]me[/]Inbox[/]DailyNotes[/]YYYY[/]MM-MMMM[/]YYYY-MM-DD` in Quick note settings.

There are two limitations that will impact this use case:

1. A quick note won't be created if the parent folder doesn't already exist
2. You'll only be able to create one quick note per day because the plug-in looks in the specified default location for previously created quick notes.

I hope that clarifies things, as I mentioned in https://github.com/jamesgreenblue/obsidian-quicknote/issues/3#issuecomment-1701053491 I don't have plans currently to expand the functionality of this plug-in beyond basic maintenance so you might want to consider a different solution.

**Comment by pcause** [comment]
thanks.
